Update MSL.py
Resolves issue 350, which is closed but not resolved.

https://github.com/asciidisco/plugin.video.netflix/issues/350

Fixes the following: "AttributeError: 'MSL' object has no attribute 'sequence_number"