Correct variable name from 'lisiting' to 'listing'
Returned variable name is incorrect and causes an error
NameError: global name 'lisiting' is not defined